version: "3.8"
services:
  serverus:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: /mnt
        target: /mnt
